In [1]:
import pandas as pd

df = pd.read_csv("job_posted_events.csv")

print(df.head())

  event_id job_id company_id          job_title   skill  skill_threshold  \
0     E001   J001       C001       Data Analyst     SQL               60
1     E002   J002       C002   Python Developer  Python               70
2     E003   J003       C003       Data Analyst   Excel               50
3     E004   J004       C001  Backend Developer  Python               80
4     E005   J005       C004      SQL Developer     SQL               75

        city      event_timestamp
0    Lucknow  2026-08-19 10:15:00
1      Delhi  2026-08-19 10:30:00
2      Noida  2026-08-19 11:00:00
3  Bangalore  2026-08-19 11:20:00
4      Delhi  2026-08-19 11:45:00

In [2]:
df.shape

(6, 8)

In [3]:
df.columns

Index(['event_id', 'job_id', 'company_id', 'job_title', 'skill',
       'skill_threshold', 'city', 'event_timestamp'],
      dtype='str')

In [4]:
df.columns

Index(['event_id', 'job_id', 'company_id', 'job_title', 'skill',
       'skill_threshold', 'city', 'event_timestamp'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         6 non-null      str
 1   job_id           6 non-null      str
 2   company_id       6 non-null      str
 3   job_title        6 non-null      str
 4   skill            6 non-null      str
 5   skill_threshold  6 non-null      int64
 6   city             6 non-null      str
 7   event_timestamp  6 non-null      str
dtypes: int64(1), str(7)
memory usage: 516.0 bytes

In [6]:
df.shape

(6, 8)

In [7]:
df.head()

,event_id,job_id,company_id,job_title,skill,skill_threshold,city,event_timestamp
0,E001,J001,C001,Data Analyst,SQL,60,Lucknow,2026-08-19 10:15:00
1,E002,J002,C002,Python Developer,Python,70,Delhi,2026-08-19 10:30:00
2,E003,J003,C003,Data Analyst,Excel,50,Noida,2026-08-19 11:00:00
3,E004,J004,C001,Backend Developer,Python,80,Bangalore,2026-08-19 11:20:00
4,E005,J005,C004,SQL Developer,SQL,75,Delhi,2026-08-19 11:45:00

In [8]:
df.tail()

,event_id,job_id,company_id,job_title,skill,skill_threshold,city,event_timestamp
1,E002,J002,C002,Python Developer,Python,70,Delhi,2026-08-19 10:30:00
2,E003,J003,C003,Data Analyst,Excel,50,Noida,2026-08-19 11:00:00
3,E004,J004,C001,Backend Developer,Python,80,Bangalore,2026-08-19 11:20:00
4,E005,J005,C004,SQL Developer,SQL,75,Delhi,2026-08-19 11:45:00
5,E006,J006,C005,Frontend Developer,JavaScript,65,Noida,2026-08-19 12:10:00

In [9]:
df.describe()

       skill_threshold
count         6.000000
mean         66.666667
std          10.801234
min          50.000000
25%          61.250000
50%          67.500000
75%          73.750000
max          80.000000

In [10]:
df.isnull().sum()

event_id           0
job_id             0
company_id         0
job_title          0
skill              0
skill_threshold    0
city               0
event_timestamp    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['job_id'].nunique()

6

In [13]:
df['company_id'].nunique()

5

In [14]:
df['skill'].unique()

<StringArray>
['SQL', 'Python', 'Excel', 'JavaScript']
Length: 4, dtype: str

In [15]:
df['city'].unique()

<StringArray>
['Lucknow', 'Delhi', 'Noida', 'Bangalore']
Length: 4, dtype: str

In [16]:
total_jobs = df['job_id'].nunique()

print("Total Jobs Posted:", total_jobs)

Total Jobs Posted: 6

In [17]:
jobs_by_city = df.groupby('city')['job_id'].nunique().sort_values(ascending=False)

print(jobs_by_city)

city
Delhi        2
Noida        2
Bangalore    1
Lucknow      1
Name: job_id, dtype: int64

In [18]:
jobs_by_skill = df.groupby('skill')['job_id'].nunique().sort_values(ascending=False)

print(jobs_by_skill)

skill
SQL           2
Python        2
JavaScript    1
Excel         1
Name: job_id, dtype: int64

In [19]:
jobs_by_company = df.groupby('company_id')['job_id'].nunique().sort_values(ascending=False)

print(jobs_by_company)

company_id
C001    2
C002    1
C003    1
C004    1
C005    1
Name: job_id, dtype: int64

In [20]:
avg_threshold = df['skill_threshold'].mean()

print("Average Skill Threshold:", avg_threshold)

Average Skill Threshold: 66.66666666666667

In [21]:
max_threshold = df['skill_threshold'].max()

print("Highest Skill Threshold:", max_threshold)

Highest Skill Threshold: 80

In [22]:
min_threshold = df['skill_threshold'].min()

print("Lowest Skill Threshold:", min_threshold)

Lowest Skill Threshold: 50

In [23]:
valid_thresholds = df[
    (df['skill_threshold'] >= 0) &
    (df['skill_threshold'] <= 100)
]

print("Valid Skill Thresholds:", len(valid_thresholds))

Valid Skill Thresholds: 6

In [24]:
invalid_thresholds = df[
    (df['skill_threshold'] < 0) |
    (df['skill_threshold'] > 100)
]

print("Invalid Skill Thresholds:", len(invalid_thresholds))

Invalid Skill Thresholds: 0

In [25]:
df['event_timestamp'] = pd.to_datetime(df['event_timestamp'])

In [26]:
print("Earliest Event:", df['event_timestamp'].min())

Earliest Event: 2026-08-19 10:15:00

In [27]:
print("Latest Event:", df['event_timestamp'].max())

Latest Event: 2026-08-19 12:10:00

In [28]:
events_by_city = df.groupby('city')['event_id'].count().sort_values(ascending=False)

print(events_by_city)

city
Delhi        2
Noida        2
Bangalore    1
Lucknow      1
Name: event_id, dtype: int64

In [29]:
print("===== JOB SUPPLY SUMMARY =====")
print("Total Jobs Posted:", df['job_id'].nunique())
print("Unique Companies:", df['company_id'].nunique())
print("Unique Skills:", df['skill'].nunique())
print("Unique Cities:", df['city'].nunique())
print("Valid Skill Thresholds:", len(valid_thresholds))
print("Invalid Skill Thresholds:", len(invalid_thresholds))
print("Average Skill Threshold:", df['skill_threshold'].mean())

===== JOB SUPPLY SUMMARY =====
Total Jobs Posted: 6
Unique Companies: 5
Unique Skills: 4
Unique Cities: 4
Valid Skill Thresholds: 6
Invalid Skill Thresholds: 0
Average Skill Threshold: 66.66666666666667

In [30]:
print("Jobs by City:")
print(jobs_by_city)

print("\nJobs by Skill:")
print(jobs_by_skill)

print("\nJobs by Company:")
print(jobs_by_company)

Jobs by City:
city
Delhi        2
Noida        2
Bangalore    1
Lucknow      1
Name: job_id, dtype: int64

Jobs by Skill:
skill
SQL           2
Python        2
JavaScript    1
Excel         1
Name: job_id, dtype: int64

Jobs by Company:
company_id
C001    2
C002    1
C003    1
C004    1
C005    1
Name: job_id, dtype: int64

In [31]:
jobs_by_city.to_csv("jobs_by_city.csv")
jobs_by_skill.to_csv("jobs_by_skill.csv")
jobs_by_company.to_csv("jobs_by_company.csv")